DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uq_evaluation_assignments_id_employee'
    ) THEN
        ALTER TABLE evaluation_assignments
            ADD CONSTRAINT uq_evaluation_assignments_id_employee
            UNIQUE (id, employee_id);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS finalized_goals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_assignment_id INTEGER NOT NULL,
    employee_id INTEGER NOT NULL,
    sequence INTEGER NOT NULL,
    title VARCHAR NULL,
    description TEXT NOT NULL,
    expectation TEXT NULL,
    success_criteria TEXT NULL,
    target_date DATE NULL,
    weight NUMERIC(10, 2) NULL,
    finalized_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_finalized_goals_employee
        FOREIGN KEY (employee_id)
        REFERENCES employees (id),
    CONSTRAINT fk_finalized_goals_source_assignment_employee
        FOREIGN KEY (source_assignment_id, employee_id)
        REFERENCES evaluation_assignments (id, employee_id)
);

CREATE INDEX IF NOT EXISTS ix_finalized_goals_source_assignment_id
    ON finalized_goals (source_assignment_id);

CREATE INDEX IF NOT EXISTS ix_finalized_goals_employee_id
    ON finalized_goals (employee_id);

CREATE TABLE IF NOT EXISTS finalized_kpis (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_assignment_id INTEGER NOT NULL,
    employee_id INTEGER NOT NULL,
    sequence INTEGER NOT NULL,
    title VARCHAR NOT NULL,
    expectation TEXT NOT NULL,
    finalized_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_finalized_kpis_employee
        FOREIGN KEY (employee_id)
        REFERENCES employees (id),
    CONSTRAINT fk_finalized_kpis_source_assignment_employee
        FOREIGN KEY (source_assignment_id, employee_id)
        REFERENCES evaluation_assignments (id, employee_id)
);

CREATE INDEX IF NOT EXISTS ix_finalized_kpis_source_assignment_id
    ON finalized_kpis (source_assignment_id);

CREATE INDEX IF NOT EXISTS ix_finalized_kpis_employee_id
    ON finalized_kpis (employee_id);
